### ISSUE TITLE
example configuration for language model.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#3] opened 2017-04-21 09:28 UTC
- In this example, we would like to show how to **train**:
    1. a n-gram language model (please refer to [this](https://github.com/lcy-seso/paddle_confs_v1/blob/master/language_model/ngram_language_model.conf) configuration file written in old PaddlePaddle API）
    2. a rnn/lstm language model  (please refer to [this](https://github.com/lcy-seso/paddle_confs_v1/blob/master/language_model/rnn_language_model.conf) configuration file written in old PaddlePaddle API)

- Besides, we would like to show how to **generate sequence** from:
    1. a N-gram language
    2. a rnn language model

- In the generation process, please consider the following two situations:
    1. generate a sequence by using [paddle.infer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/inference.py#L73) API, in which you need to implement one-way search or beam search (beam search is more complicated, I suggest to implement one-way search first.)
    2. generate a sequence by using recurrent_layer_group

- Please consider to use the following data for training and add these datasets into `paddle.dataset` package.
    1. [1billionword-training](https://github.com/ciprian-chelba/1-billion-word-language-modeling-benchmark), [1 billionword-test](https://github.com/tensorflow/models/tree/master/lm_1b) 
    2. [ptb](https://github.com/facebook/SCRNNs)

- Please pull your codes and docs into the [language_model](https://github.com/PaddlePaddle/models/tree/develop/language_model) directory.

**Comment by lcy-seso** [comment] 2017-04-21 12:37
please consider this issue https://github.com/PaddlePaddle/Paddle/issues/1814.

**Comment by chengxiaohua1105** [comment] 2017-04-24 09:48
我认领这个case

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
