### ISSUE TITLE
Doc discussion.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/models#806] opened 2018-04-03 02:59 UTC
The basic document specification is as follows, but not limited to.
The doc of  DeepSpeech (https://github.com/paddlepaddle/deepspeech) is a good reference.
The following is just an example. Each model can adjust flexibly.

---
At first, declare the version of Paddle. For example:

The minimum PaddlePaddle version needed for the code sample in this directory is v0.10.0. If you are on a version of PaddlePaddle earlier than v0.10.0, [please update your installation](http://www.paddlepaddle.org/docs/develop/documentation/en/build_and_install/pip_install_en.html).

## Introduction
The introduction of model structure.  But not limited to.

## Data Preparation
If download data automatically,  skip this part.

### Data Augmentation Pipeline
Describe the data augmentation pipeline, but not limited to.
Better have the convergent curve

## Evaluation
How to test model.
## Inference and Visualization
How to do inference by Python API.
Better to visualize the results.
## Finetuning
How to load a model to fine-tune.
## Released Models
  Need the URL of Released Models

**Comment by chengduoZH** [comment] 2018-04-04 07:09
I have three question:
1. How about adding `Data Augmentation Pipeline`?
2. This doc needs to introduce how to do distributed cloud training?
3. This doc needs to display multi-card speedup?

**Comment by qingqing01** [comment] 2018-04-09 02:27
@chengduoZH Thanks!

I added the first one.

About 2, this can be added in the future when the distributed cloud training is ready.
About 3, since we have benchmark,  the speedup for multi-GPUs can be added here or not.

**Comment by shanyi15** [comment] 2018-08-15 09:55
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:55 UTC
