### ISSUE TITLE
lambda_cost NCG_DIFF 计算公式为什么和论文中公式不一样

### ISSUE THREAD

**Issue by superzhangmch** [PaddlePaddle/models#207] opened 2017-08-16 03:45 UTC
Paddle/paddle/gserver/layers/CostLayer.cpp 中 lambda_cost NCG_DIFF 计算：
        dcgDif = (std::pow(2, score_i) - std::pow(2, score_j)) /  (std::log(i + 2) - std::log(j + 2));
lambdarank paper 中
       dcgDif = (2^score_i - 2^score_j) * (1/log(i+2) - 1/ log(j+2))
为什么有这种差异？
（自己实现lambda cost玩发现效果还不如rank net。看到如上差异，难道原因在此？）

**Comment by lcy-seso** [comment] 2017-09-21 10:10
maybe, when implementing the lambda rank op, @kuke can help check this formula.

**Comment by shanyi15** [comment] 2018-08-15 09:58
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
Labels: user
