### ISSUE TITLE
The convergence comparison between Fluid and Houyi

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/models#676] opened 2018-03-01 04:13 UTC
To verify the correctness, we take about 1/13 training data, and carry out the contrast training of models on one single GPU with Adam optimizer. The benchmark is the model on the internal framework Houyi developed by the Speech team.

Setting:

```
batch_size: 32
device: GPU
hidden_dim: 1024
learning_rate: 0.00016
minimum_batch_size: 1
parallel: False
proj_dim: 512
stacked_num: 5
```

![training_acc](https://user-images.githubusercontent.com/3064195/36826671-efcc84fa-1d49-11e8-9826-7739f7a3972c.png)

The comparion shows that the two learning curvers match with each other very well. And we verify the convergence of DeepASR on part of training data.

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:56 UTC
Labels: DeepASR
