### ISSUE TITLE
Basic Requirements on examples added into this repo.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#1] opened 2017-04-21 02:52 UTC
# Goals
Goals of example configuration files are twofold:
1. Example configuration file is a kind of documentations to some extent, which shows how to use layers/pre-defined small networks in PaddlePaddle through examples. It is expected to be more lightweight than PaddleBook.
  
2. Backup of configuration files for newly developed layers/modules. Every time, if anyone adds a new layer into PaddlePaddle, or add a new pre-defined network into the paddle python package, he must have written a test configuration file. This test configuration file is also a good example to show how to use his new layer/network for other users.

# Basic Requirements

1. Each example has its own directory, and (optional) some complicated examples may have sub-directory.
2.  Each example should have at least two files
    - the model configuration, which includes the definition of the network topology, the optimization algorithm, the PaddlePaddle trainer, and how to read the data.
    - a README doc.
3. Each example should be tested without bugs.

# About training/testing data
-  always consider using dataset in paddle.dataset package first.
-  If there is no appropriate dataset in paddle.dataset package, give a description of the format of the input data

# Requirements on the README doc
- The REAMDE doc should have at least the following two sections:
    1. **Brief introduction**. The introduction should include:
           - what task does the configuration file for?
           - If the example does not provide data for training, it should provide descriptions about the format of the training data, and give an example to at least one training data.
    2. **Explanation about the model architecture**.  A picture to show the model architecture, or refer to a certain reference. Chose a convenient way to make some explanations about the model architecture to let other know about why do you write the example and what the example wants to explain. 
    3. [**optional**] How to run, but try to provide such an explanation as much as possible.

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
