### ISSUE TITLE
for logistic regreetion, got "ValueError: The input should be a vector, please check your input data."

### ISSUE THREAD

**Issue by 690609237** [PaddlePaddle/models#500] opened 2017-11-29 03:11 UTC
```python
1. def reader():
2.          UNK_ID = word_dict["<UNK>"]
3.          word_col = 1
4.          teacher_label_col = 0
5.          for file_name in os.listdir(data_dir):
6.              with open(os.path.join(data_dir, file_name), "r") as f:
7.                       for line in f:
8.                      line_split = line.strip().split("\t")
9.                      word_ids = [
10.                          word_dict.get(w, UNK_ID)
11.                         for w in line_split[word_col].split() ]
12.                      y_value = float(line_split[teacher_label_col])
13.                     yield word_ids, y_value
14.      return reader
```
this is my reader code, y_value is float type, x value is writed as words_ids like [12, 34, 55]. when run got "ValueError:The input should be a vector, please check your input data." when I try to replace the line 12 to "y_value = [float(line_split[teacher_label_col])]" , got a core bug..

**Comment by wangkuiyi** [comment] 2018-03-10 18:16
Hello @690609237 , we are sorry for the very late reply. Is this still a concern?  Thanks!

**Comment by shanyi15** [comment] 2018-08-15 09:57
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:57 UTC
Labels: user
