### ISSUE TITLE
how to use pre-commit scripts to auto-format the code?

### ISSUE THREAD

**Issue by likesiwell** [PaddlePaddle/models#953] opened 2018-05-31 13:01 UTC
I try to contribute a new paddle implementation, but when I run pre-commit, there is always a yapf failed case and I don't know what happened. 
I create a new issue to PR the project, but PR shows The Travis CI build failed.
Could anyone tell me what happened? 

[The Travis CI build failed message](https://travis-ci.org/PaddlePaddle/models/builds/386154623?utm_source=github_status&utm_medium=notification)
![image](https://user-images.githubusercontent.com/8766415/40783674-c98f07ea-6515-11e8-8f92-ee446c151ad5.png)

![image](https://user-images.githubusercontent.com/8766415/40783666-c1eadae6-6515-11e8-8a51-18125d455b68.png)

**Comment by luotao1** [comment] 2018-05-31 13:19
you can `git add fluid/image_classification/caffe2fluid/kaffe/graph.py` again, then `git commit`

**Comment by likesiwell** [comment] 2018-05-31 13:27
how to know **what and where** the error with my code is to pass the pre-commit? 
Does pre-commit automatically format the code?

**Comment by luotao1** [comment] 2018-05-31 13:32
> how to know what and where the error with my code is to pass the pre-commit

![image](https://user-images.githubusercontent.com/6836917/40785040-f8de335a-6519-11e8-9bc8-3497d153fe7e.png)
This is the diff.

> Does pre-commit automatically format the code?

Yes, automatically.

For more details, you can refer to http://www.paddlepaddle.org/docs/develop/documentation/en/dev/contribute_to_paddle_en.html#workflow

**Comment by likesiwell** [comment] 2018-05-31 13:37
Thanks, I have tried to contribute the code following the instruction of this document, but failed. And now I don't know what's wrong.
Do you think the failure is caused by graph.py or my code?

**Comment by luotao1** [comment] 2018-06-01 02:02
what's wrong with you now? If the failure is caused by graph.py, you can follow https://github.com/PaddlePaddle/models/issues/953#issuecomment-393527192

**Comment by likesiwell** [comment] 2018-06-01 03:25
When I use 
> you can git add fluid/image_classification/caffe2fluid/kaffe/graph.py again, then git commit

the graph.py will be automatically formatted. I can't push the unchanged version of graph.py. I don't know how to solve this.

**Comment by shanyi15** [comment] 2018-08-15 10:05
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:05 UTC
Labels: user
