### ISSUE TITLE
Memory leaking of deepspeech2

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/models#234] opened 2017-09-07 10:43 UTC
Here is my command:
`python train.py --use_gpu=False --num_passes=1 --trainer_count=1 --batch_size=512 --num_iter_print=1 --num_proc_data=4`

I did not train with GPU, and only give 1`trainer_count` and 4 `num_proc_data`, which should makes the thing easy.

Total available memory of my system is 62.6G.

When stat to train,  I found the memory percent from ~50% increasing to 99%, then killed by system.

Is this possible that some memory leaking ?

> 
> Pass: 0, Batch: 1, TrainCost: 221.743195
> I0907 17:58:52.262146 50789 Thread.h:271] SyncThreadPool worker thread 0
> 
> Pass: 0, Batch: 2, TrainCost: 745.176697
> 
> Pass: 0, Batch: 3, TrainCost: 217.676758
> Killed

PaddlePaddle version:

> commit a072ab9e74227361421e6b1fdc167b6709fcdf87
Date:   Thu Sep 7 11:10:47 2017 +0800

DeepSpeech2 version:

> commit acea40b6d1a23cb4923dc82ad7c0428a832406e2
Date:   Wed Sep 6 20:32:20 2017 +0800

**Comment by tensor-tang** [comment] 2017-09-07 11:52
Addition:
Retest with batch size 256 which is default setting.

`py train.py --use_gpu=False --num_passes=1 --trainer_count=1 --batch_size=256 --num_iter_print=1 --num_proc_data=4`

This time goes more batches but still failed, same issue.
Memory usage started from lower percentage but goes more and more in training.

> ...
> Pass: 0, Batch: 19, TrainCost: 390.265625
> 
> Pass: 0, Batch: 20, TrainCost: 398.598969
> Killed

**Comment by xinghai-sun** [comment] 2017-09-07 14:59
Thanks for reporting this problem.

Yes. We have also found a slight GPU memory leakage when training with GPUs, but very slightly,  maybe  far less than 10%. But not aware of the leakage of main memory. 

We'll check it tomorrow.

**Comment by pkuyym** [comment] 2017-09-15 02:42
@tensor-tang One of my colleagues has also encountered this problem when using PaddlePaddle to do object detection task. We debugged a lot and found that when compiled in some platform (or environment) PaddlePaddle may have memory leakage, however the specify reason hasn't been figure out. I suggest you can retry your experiments in our released docker image.

**Comment by tensor-tang** [comment] 2017-09-15 03:12
@pkuyym 
There is one point that I should emphasize: I did not encounter this issue about one month ago.

Either it is caused by commits of DS2 itself around this month, or PaddlePaddle around this month.
So maybe is a clue for you is track this issue.

**Comment by shanyi15** [comment] 2018-08-15 09:58
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
Labels: need be discussed
