### ISSUE TITLE
请问这里的demo直接不能跑成功吗，alexnet跑flowers数据集，报错、不收敛

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/models#699] opened 2018-03-08 07:11 UTC
跑image_classification原汁原味的程序（单机cpu，PaddlePaddle 0.10.0，默认参数），python train.py alexnet （vgg13也是）
![5e2f5e2f-9d86-4512-8738-b0f3faeae14a](https://user-images.githubusercontent.com/1950292/37137502-f160d4be-22e0-11e8-9c45-bec82e266b8a.JPG)

1、看别的issue，这种情况貌似要添加bn；难道示例提供的demo程序和数据没有试验过吗
2、添加bn，不报错但貌似还是不收敛
![62b4e58e-10c2-4d8b-9782-3a3c271bde2f](https://user-images.githubusercontent.com/1950292/37137913-e5040752-22e2-11e8-82cd-79dde5950283.JPG)
![ad488cb1-14e8-4e0e-a834-bd844a0de601](https://user-images.githubusercontent.com/1950292/37137920-ead184d4-22e2-11e8-985d-653b94297854.JPG)

3、请问demo还需要做哪些改动；如果demo是好的，请问多少轮能收敛到什么程度（现在跑的不够？）

**Comment by ranqiu92** [comment] 2018-03-08 12:43
你跑了几个pass

**Comment by Kayven** [comment] 2018-03-09 02:47
11个pass的日志如下
![11](https://user-images.githubusercontent.com/1950292/37187865-4bf877dc-2387-11e8-8b85-709a081392dd.JPG)

**Comment by Kayven** [comment] 2018-03-09 02:54
488 Pass 13, Batch 9, Cost 4.516739, {'classification_error_evaluator': 0.9609375}
489 
490 Pass 13, Batch 12, Cost 4.467812, {'classification_error_evaluator': 0.9609375}
491 
492 Pass 13, Batch 15, Cost 4.477870, {'classification_error_evaluator': 0.9140625}
493 
494 Pass 13, Batch 18, Cost 4.454433, {'classification_error_evaluator': 0.9921875}
495 
496 Pass 13, Batch 21, Cost 4.493628, {'classification_error_evaluator': 0.9765625}
497 
498 Pass 13, Batch 24, Cost 4.378610, {'classification_error_evaluator': 0.9453125}
499 
500 Pass 13, Batch 27, Cost 4.397795, {'classification_error_evaluator': 0.9765625}
501 
502 Pass 13, Batch 30, Cost 4.411468, {'classification_error_evaluator': 0.9921875}
503 
504 Pass 13, Batch 33, Cost 4.404350, {'classification_error_evaluator': 0.9609375}
505 
506 Pass 13, Batch 36, Cost 4.548743, {'classification_error_evaluator': 0.9453125}
507 
508 Pass 13, Batch 39, Cost 4.358288, {'classification_error_evaluator': 0.9296875}
509 
510 Pass 13, Batch 42, Cost 4.393285, {'classification_error_evaluator': 0.9609375}
511 
512 Pass 13, Batch 45, Cost 4.456183, {'classification_error_evaluator': 0.984375}
513 
514 Pass 13, Batch 48, Cost 4.643979, {'classification_error_evaluator': 1.0}
515 
516 Test with Pass 13, {'classification_error_evaluator': 0.9901960492134094}
517 
518 Pass 14, Batch 0, Cost 4.351240, {'classification_error_evaluator': 0.9609375}
519 
520 Pass 14, Batch 3, Cost 4.343180, {'classification_error_evaluator': 0.96875}
521 
522 Pass 14, Batch 6, Cost 4.406670, {'classification_error_evaluator': 0.9453125}
523

**Comment by Kayven** [comment] 2018-03-09 02:55
Pass 23, Batch 30, Cost 3.982112, {'classification_error_evaluator': 0.890625}

Pass 23, Batch 31, Cost 3.911903, {'classification_error_evaluator': 0.9140625}

Pass 23, Batch 32, Cost 3.979963, {'classification_error_evaluator': 0.921875}

Pass 23, Batch 33, Cost 3.965095, {'classification_error_evaluator': 0.8828125}

Pass 23, Batch 34, Cost 4.060487, {'classification_error_evaluator': 0.96875}

Pass 23, Batch 35, Cost 3.996348, {'classification_error_evaluator': 0.8984375}

Pass 23, Batch 36, Cost 3.953127, {'classification_error_evaluator': 0.921875}

Pass 23, Batch 37, Cost 3.923328, {'classification_error_evaluator': 0.921875}

Pass 23, Batch 38, Cost 3.937922, {'classification_error_evaluator': 0.8828125}

Pass 23, Batch 39, Cost 3.992517, {'classification_error_evaluator': 0.9375}

Pass 23, Batch 40, Cost 4.008447, {'classification_error_evaluator': 0.9375}

Pass 23, Batch 41, Cost 3.981569, {'classification_error_evaluator': 0.9375}

Pass 23, Batch 42, Cost 3.947819, {'classification_error_evaluator': 0.9296875}

Pass 23, Batch 43, Cost 3.894287, {'classification_error_evaluator': 0.8984375}

Pass 23, Batch 44, Cost 4.079328, {'classification_error_evaluator': 0.9375}

Pass 23, Batch 45, Cost 4.054526, {'classification_error_evaluator': 0.9140625}

Pass 23, Batch 46, Cost 3.946394, {'classification_error_evaluator': 0.9140625}

Pass 23, Batch 47, Cost 3.950107, {'classification_error_evaluator': 0.9296875}

Pass 23, Batch 48, Cost 4.531033, {'classification_error_evaluator': 1.0}

Test with Pass 23, {'classification_error_evaluator': 0.977450966835022}
                                                                                                                                                      
Pass 24, Batch 0, Cost 3.983666, {'classification_error_evaluator': 0.9375}                                                                           
                                                                                                                                                      
Pass 24, Batch 1, Cost 3.863604, {'classification_error_evaluator': 0.921875}

**Comment by Kayven** [comment] 2018-03-09 02:55
```
367 
368 Pass 9, Batch 45, Cost 4.429246, {'classification_error_evaluator': 0.96875}
369 
370 Pass 9, Batch 48, Cost 4.365916, {'classification_error_evaluator': 1.0}
371 
372 Test with Pass 9, {'classification_error_evaluator': 0.9901960492134094}
373 
374 Pass 10, Batch 0, Cost 4.369379, {'classification_error_evaluator': 0.9609375}
375 
376 Pass 10, Batch 3, Cost 4.470682, {'classification_error_evaluator': 0.9609375}
377 
378 Pass 10, Batch 6, Cost 4.404115, {'classification_error_evaluator': 0.9609375}
379 
380 Pass 10, Batch 9, Cost 4.431010, {'classification_error_evaluator': 0.96875}
381 
382 Pass 10, Batch 12, Cost 4.468472, {'classification_error_evaluator': 0.9765625}
383 
384 Pass 10, Batch 15, Cost 4.540837, {'classification_error_evaluator': 0.9765625}
385 
386 Pass 10, Batch 18, Cost 4.404477, {'classification_error_evaluator': 0.953125}
387 
388 Pass 10, Batch 21, Cost 4.511425, {'classification_error_evaluator': 0.9453125}
389 
390 Pass 10, Batch 24, Cost 4.455076, {'classification_error_evaluator': 0.984375}
391 
392 Pass 10, Batch 27, Cost 4.500587, {'classification_error_evaluator': 0.9609375}
393 
394 Pass 10, Batch 30, Cost 4.391237, {'classification_error_evaluator': 0.96875}
395 
396 Pass 10, Batch 33, Cost 4.426351, {'classification_error_evaluator': 0.9375}
397 
398 Pass 10, Batch 36, Cost 4.502441, {'classification_error_evaluator': 0.9609375}
399 
400 Pass 10, Batch 39, Cost 4.435919, {'classification_error_evaluator': 0.96875}
401                                                                                                                                                   
402 Pass 10, Batch 42, Cost 4.345354, {'classification_error_evaluator': 0.9453125}                                                                   
403                                                                                                                                                   
404 Pass 10, Batch 45, Cost 4.411730, {'classification_error_evaluator': 0.9765625}                                                                   
405                                                                                                                                                   
406 Pass 10, Batch 48, Cost 4.935240, {'classification_error_evaluator': 1.0}                                                                         
407                                                                                                                                                   
408 Test with Pass 10, {'classification_error_evaluator': 0.9901960492134094}                                                                         
409                                                                                                                                                   
410 Pass 11, Batch 0, Cost 4.376519, {'classification_error_evaluator': 0.96875}   
```

**Comment by ranqiu92** [comment] 2018-03-09 03:09
可以调下超参数试下，比如学习率等等

**Comment by Kayven** [comment] 2018-03-09 03:14
试过了

而且我最主要的问题是，给的demo还需要各种调试才能跑通吗

**Comment by Kayven** [comment] 2018-03-09 03:15
学习率调到0.0001都差不多

**Comment by Kayven** [comment] 2018-03-09 03:17
或者你们有没有跑成功过的，包括调过的参数或结构，给我试一下。

**Comment by ranqiu92** [comment] 2018-03-09 07:33
调参时可能得多试几个值，实验可能需要看多跑几个pass的现象。学习率调到0.001时试下，我运行的部分log如下：
```
Pass 20, Batch 19, Cost 2.289397, {'classification_error_evaluator': 0.6015625}

Pass 20, Batch 20, Cost 2.072517, {'classification_error_evaluator': 0.5234375}

Pass 20, Batch 21, Cost 2.381744, {'classification_error_evaluator': 0.625}

Pass 20, Batch 22, Cost 2.234521, {'classification_error_evaluator': 0.59375}

Pass 20, Batch 23, Cost 2.313380, {'classification_error_evaluator': 0.65625}

Pass 20, Batch 24, Cost 2.446400, {'classification_error_evaluator': 0.6953125}

Pass 20, Batch 25, Cost 2.313638, {'classification_error_evaluator': 0.6328125}

Pass 20, Batch 26, Cost 2.087145, {'classification_error_evaluator': 0.6328125}
```

**Comment by Kayven** [comment] 2018-03-09 08:21
1、我前面已经提供了pass=23的情况，我们还跑过100多轮。（当然学习率是0.1没调）
Pass 23, Batch 47, Cost 3.950107, {'classification_error_evaluator': 0.9296875}
Pass 23, Batch 48, Cost 4.531033, {'classification_error_evaluator': 1.0}
Test with Pass 23, {'classification_error_evaluator': 0.977450966835022}


2、不加bn每次都报错（3个机器），而你这里不需要加bn就能正常；这个问题一直没有解答。

3、希望相关人员能耐心帮忙看下。我及同事在3台机器试了快一个星期了（本身单机就慢），调学习率、dropout、换模型，只可惜有些没保留日志。
而上面回复一直让我们调参；我们觉得这样一个知名的工具本身跑的结果不正常，应该不是参数的问题；调参有可能是缘木求鱼，况且已经说过试过很多次了。

**Comment by Kayven** [comment] 2018-03-09 08:23
我感觉不收敛更多可能是加了bn导致的

**Comment by ranqiu92** [comment] 2018-03-09 08:37
你在学习率0.001  使用原始代码不做修改，alexnet的跑的结果是怎样的

**Comment by Kayven** [comment] 2018-03-09 09:52
下面是0.001学习率不加bn。
挺慢的，现在只有你能贴下5个pass时的数据，我对比下

Pass 3, Batch 41, Cost 4.396451, {'classification_error_evaluator': 0.9609375}

Pass 3, Batch 42, Cost 4.450082, {'classification_error_evaluator': 0.9921875}

Pass 3, Batch 43, Cost 4.388668, {'classification_error_evaluator': 0.9375}

Pass 3, Batch 44, Cost 4.368311, {'classification_error_evaluator': 0.984375}

Pass 3, Batch 45, Cost 4.400636, {'classification_error_evaluator': 0.9765625}

Pass 3, Batch 46, Cost 4.437011, {'classification_error_evaluator': 0.96875}

Pass 3, Batch 47, Cost 4.450068, {'classification_error_evaluator': 0.9609375}

Pass 3, Batch 48, Cost 4.130972, {'classification_error_evaluator': 1.0}

Test with Pass 3, {'classification_error_evaluator': 0.9852941036224365}

Pass 4, Batch 0, Cost 4.513779, {'classification_error_evaluator': 0.9921875}

Pass 4, Batch 1, Cost 4.424250, {'classification_error_evaluator': 0.9765625}

Pass 4, Batch 2, Cost 4.351628, {'classification_error_evaluator': 0.9375}

Pass 4, Batch 3, Cost 4.446166, {'classification_error_evaluator': 0.96875}

Pass 4, Batch 4, Cost 4.397869, {'classification_error_evaluator': 0.9609375}

Pass 4, Batch 5, Cost 4.371132, {'classification_error_evaluator': 0.9609375}

Pass 4, Batch 6, Cost 4.389667, {'classification_error_evaluator': 0.9609375}

Pass 4, Batch 7, Cost 4.347771, {'classification_error_evaluator': 0.95312

**Comment by yeyupiaoling** [comment] 2018-03-09 12:21
@Kayven 
加了`BN`层不收敛，这我也试过，把`BN`层关了就行`conv_with_batchnorm=False`。还有我看到你的模型是收敛的。

**Comment by Kayven** [comment] 2018-03-09 12:49
@ranqiu92  “学习率0.001 使用原始代码不做修改”可以跑不报错，看上去test error是在减少，应该是可以了。

不过还是不知道为什么原始的0.1不行，跟机器内核或者什么库有关吗，为什么你能直接跑。
如果我还是想把学习率调大，该怎么弄跑成功？

**Comment by Kayven** [comment] 2018-03-09 12:50
@yeyupiaoling 把fc之间的bn层去掉，然后在img_conv_group函数里加conv_with_batchnorm=False？

**Comment by yeyupiaoling** [comment] 2018-03-09 12:53
@Kayven
>为什么你能直接跑

我估计他是使用了`BN`层，使用`BN`层可以使用较大的学习率，也不会报浮点异常

> 把fc之间的bn层去掉，然后在img_conv_group函数里加conv_with_batchnorm=False？

是的

**Comment by shanyi15** [comment] 2018-08-15 09:55
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:55 UTC
Labels: user
