### ISSUE TITLE
tiny文件夹中 run_train.sh 运行错误

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#389] opened 2017-10-18 07:42 UTC
![image](https://user-images.githubusercontent.com/7878465/31706255-ef0bb0d2-b3ad-11e7-9031-2eaed2fb920e.png)

**Comment by kuke** [comment] 2017-10-19 05:01
按报错来看应该是CUDA驱动版本过低，请尝试一下升级CUDA driver。

**Comment by lezasantaizi** [comment] 2017-10-20 02:47
我没有使用gpu哈，不使用gpu也需要升级cuda吗？

**Comment by lezasantaizi** [comment] 2017-10-20 03:06
Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version

**Comment by kuke** [comment] 2017-10-20 03:33
@lezasantaizi 这个docker镜像是GPU版，得用nvidia-docker运行。后面我们可以发布一个CPU版的镜像

**Comment by lezasantaizi** [comment] 2017-10-20 04:06
原来如此，多谢回复🙏！啥时候会发cpu版本的哈？

**Comment by shanyi15** [comment] 2018-08-15 10:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:11 UTC
