### ISSUE TITLE
fluid/ocr_recognition例子的模型训练脚本缺少几个命令行参数解析

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/models#964] opened 2018-06-05 05:35 UTC
[models/fluid/ocr_recognition](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition)例子中的模型训练脚本ctc_train.py，缺少文档中提及的几个命令行参数的接收与解析过程。
![1](https://user-images.githubusercontent.com/6863219/40956334-4be30598-68c2-11e8-8f99-ad74235e1c6b.png)
![2](https://user-images.githubusercontent.com/6863219/40956336-4e463a4e-68c2-11e8-9488-326b245bbd17.png)

**Comment by shanyi15** [comment] 2018-08-15 10:05
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:05 UTC
