### ISSUE TITLE
Add pointer to models in paddle book

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/models#401] opened 2017-10-25 07:44 UTC
Models such as NMT with attention is not included in this repo but present in paddle book. I think it will be convenient for the users if we add some links to these models in this repo. Otherwise, some users may feel confused why such useful models are absent in this repo.

**Comment by lcy-seso** [comment] 2017-10-25 07:48
Maybe we can update the README. 
There are also [scheduled sampling](https://github.com/PaddlePaddle/models/tree/develop/scheduled_sampling), [generate_chinese_poetry](https://github.com/PaddlePaddle/models/tree/develop/generate_chinese_poetry), which are all attention models.

**Comment by shanyi15** [comment] 2018-08-15 09:57
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:57 UTC
