### ISSUE TITLE
image_classification vgg13 Check failed: (size_t)lbl[i] < dim (102 vs. 102)

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/models#147] opened 2017-07-05 06:39 UTC
```
➜  image_classification git:(develop) ✗ python train.py vgg13
/home/lizhao/.jumbo/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:28: UserWarning: This platform l
acks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 37
70..  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
I0705 14:23:52.511775  6784 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-07-05 14:23:52,518 layers.py:2412] output for __conv_0__: c = 64, h = 224, w = 224, size = 3211264
[INFO 2017-07-05 14:23:52,519 layers.py:2412] output for __conv_1__: c = 64, h = 224, w = 224, size = 3211264
[INFO 2017-07-05 14:23:52,520 layers.py:2537] output for __pool_0__: c = 64, h = 112, w = 112, size = 802816
[INFO 2017-07-05 14:23:52,521 layers.py:2412] output for __conv_2__: c = 128, h = 112, w = 112, size = 1605632
[INFO 2017-07-05 14:23:52,522 layers.py:2412] output for __conv_3__: c = 128, h = 112, w = 112, size = 1605632
[INFO 2017-07-05 14:23:52,523 layers.py:2537] output for __pool_1__: c = 128, h = 56, w = 56, size = 401408
[INFO 2017-07-05 14:23:52,524 layers.py:2412] output for __conv_4__: c = 256, h = 56, w = 56, size = 802816
[INFO 2017-07-05 14:23:52,525 layers.py:2412] output for __conv_5__: c = 256, h = 56, w = 56, size = 802816
[INFO 2017-07-05 14:23:52,526 layers.py:2537] output for __pool_2__: c = 256, h = 28, w = 28, size = 200704
[INFO 2017-07-05 14:23:52,527 layers.py:2412] output for __conv_6__: c = 512, h = 28, w = 28, size = 401408
[INFO 2017-07-05 14:23:52,528 layers.py:2412] output for __conv_7__: c = 512, h = 28, w = 28, size = 401408
[INFO 2017-07-05 14:23:52,529 layers.py:2537] output for __pool_3__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-07-05 14:23:52,530 layers.py:2412] output for __conv_8__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-07-05 14:23:52,531 layers.py:2412] output for __conv_9__: c = 512, h = 14, w = 14, size = 100352
[INFO 2017-07-05 14:23:52,532 layers.py:2537] output for __pool_4__: c = 512, h = 7, w = 7, size = 25088
I0705 14:23:55.889189  6784 GradientMachine.cpp:85] Initing parameters..
I0705 14:24:04.664135  6784 GradientMachine.cpp:92] Init parameters done.
F0705 14:28:51.952270  6784 Matrix.cpp:3286] Check failed: (size_t)lbl[i] < dim (102 vs. 102)
*** Check failure stack trace: ***
    @     0x7f01d1fa231d  google::LogMessage::Fail()
    @     0x7f01d1fa5dcc  google::LogMessage::SendToLog()
    @     0x7f01d1fa1e43  google::LogMessage::Flush()
    @     0x7f01d1fa72de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f01d1dfe6b0  paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f01d1d288e5  paddle::CostLayer::forward()
    @     0x7f01d1d996f0  paddle::NeuralNetwork::forward()
    @     0x7f01d1d75433  paddle::GradientMachine::forwardBackward()
    @     0x7f01d1f7db7b  GradientMachine::forwardBackward()
    @     0x7f01d1bf87ce  _wrap_GradientMachine_forwardBackward
    @     0x7f01dab763a3  PyEval_EvalFrameEx
    @     0x7f01dab78130  PyEval_EvalCodeEx
    @     0x7f01dab764a1  PyEval_EvalFrameEx
    @     0x7f01dab78130  PyEval_EvalCodeEx
    @     0x7f01dab764a1  PyEval_EvalFrameEx
    @     0x7f01dab78130  PyEval_EvalCodeEx
    @     0x7f01dab764a1  PyEval_EvalFrameEx
    @     0x7f01dab78130  PyEval_EvalCodeEx
    @     0x7f01dab764a1  PyEval_EvalFrameEx
    @     0x7f01dab78130  PyEval_EvalCodeEx
    @     0x7f01dab78242  PyEval_EvalCode
    @     0x7f01dab9262c  run_mod
    @     0x7f01dab92700  PyRun_FileExFlags
    @     0x7f01dab93c0c  PyRun_SimpleFileExFlags
    @     0x7f01daba54cc  Py_Main
    @       0x318ae1ecdd  (unknown)
Thread [139645940217600] Forwarding __cost_0__,
*** Aborted at 1499236132 (unix time) try "date -d @1499236132" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x20900001a80) received by PID 6784 (TID 0x7f01daa93700) from PID 6784; stack trace: ***
    @       0x318b20f500 (unknown)
    @       0x318ae328a5 (unknown)
    @       0x318ae34085 (unknown)
    @     0x7f01d1fac85b google::FindSymbol()
    @     0x7f01d1fad21a google::GetSymbolFromObjectFile()
    @     0x7f01d1fad8e2 google::SymbolizeAndDemangle()
    @     0x7f01d1fab0e8 google::DumpStackTrace()
    @     0x7f01d1fab1a6 google::DumpStackTraceAndExit()
    @     0x7f01d1fa231d google::LogMessage::Fail()
    @     0x7f01d1fa5dcc google::LogMessage::SendToLog()
    @     0x7f01d1fa1e43 google::LogMessage::Flush()
    @     0x7f01d1fa72de google::LogMessageFatal::~LogMessageFatal()
    @     0x7f01d1dfe6b0 paddle::CpuMatrix::oneHotCrossEntropy()
    @     0x7f01d1d288e5 paddle::CostLayer::forward()
    @     0x7f01d1d996f0 paddle::NeuralNetwork::forward()
    @     0x7f01d1d75433 paddle::GradientMachine::forwardBackward()
    @     0x7f01d1f7db7b GradientMachine::forwardBackward()
    @     0x7f01d1bf87ce _wrap_GradientMachine_forwardBackward
    @     0x7f01dab763a3 PyEval_EvalFrameEx
    @     0x7f01dab78130 PyEval_EvalCodeEx
    @     0x7f01dab764a1 PyEval_EvalFrameEx
    @     0x7f01dab78130 PyEval_EvalCodeEx
    @     0x7f01dab764a1 PyEval_EvalFrameEx
    @     0x7f01dab78130 PyEval_EvalCodeEx
    @     0x7f01dab764a1 PyEval_EvalFrameEx
    @     0x7f01dab78130 PyEval_EvalCodeEx
    @     0x7f01dab764a1 PyEval_EvalFrameEx
    @     0x7f01dab78130 PyEval_EvalCodeEx
    @     0x7f01dab78242 PyEval_EvalCode
    @     0x7f01dab9262c run_mod
    @     0x7f01dab92700 PyRun_FileExFlags
    @     0x7f01dab93c0c PyRun_SimpleFileExFlags
[1]    6784 abort (core dumped)  python train.py vgg13
```

**Comment by shanyi15** [comment] 2018-08-15 10:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:08 UTC
