### ISSUE TITLE
AttributeError: 'module' object has no attribute 'elementwise_mul'

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/models#603] opened 2018-01-27 05:56 UTC
When I run https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/se_resnext.py,
I met an error:
```
Traceback (most recent call last):
  File "se_resnext.py", line 160, in <module>
    train(learning_rate=0.1, batch_size=8, num_passes=100)
  File "se_resnext.py", line 110, in train
    out = SE_ResNeXt(input=image, class_dim=class_dim)
  File "se_resnext.py", line 91, in SE_ResNeXt
    reduction_ratio=reduction_ratio)
  File "se_resnext.py", line 62, in bottleneck_block
    reduction_ratio=reduction_ratio)
  File "se_resnext.py", line 31, in squeeze_excitation
    scale = fluid.layers.elementwise_mul(x=input, y=excitation, axis=0)
AttributeError: 'module' object has no attribute 'elementwise_mul'
```

The PaddlePaddle is installed by `pip install paddlepaddle` and the version is 0.11.
It seems that it needs a new PaddlePaddle version.

Since `models` are used for end users, maybe we need to test our implement from the user's point of view.

**Comment by luotao1** [comment] 2018-01-29 01:56
Discussed with @lcy-seso before, since models repo is always updated/added/modified with the develop branch of PaddlePaddle, it is difficult to use a fixed version. Maybe we can add an explanation of the models repo.

**Comment by shanyi15** [comment] 2018-08-15 10:10
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:11 UTC
