### ISSUE TITLE
caffe2fluid can't generate fluid model from caffe

### ISSUE THREAD

**Issue by sabreshao** [PaddlePaddle/models#896] opened 2018-05-09 08:07 UTC
1. Install protobuf pip: $pip install protobuf
2. Prepare caffepb.py: $ cd [root]/fluid/image_classification/caffe2fluid/proto && wget https://github.com/ethereon/caffe-tensorflow/raw/master/kaffe/caffe/caffepb.py
3. Run convert.py: $ cd [root]/fluid/image_classification/caffe2fluid &&  python convert.py alexnet.prototxt --caffemodel alexnet.caffemodel --data-output-path alexnet.npy --code-output-path alexnet.py

Error message:

register layer[Axpy]
register layer[Flatten]
register layer[ArgMax]
register layer[Reshape]
Traceback (most recent call last):
  File "convert.py", line 80, in <module>
    ret = main()
  File "convert.py", line 76, in main
    args.code_output_path, args.phase)
  File "convert.py", line 35, in convert
    transformer = Transformer(def_path, caffemodel_path, phase=phase)
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 287, in __init__
    self.load(def_path, data_path, phase)
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 293, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 167, in __init__
    self.load()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 171, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 43, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 18, in __init__
    self.import_caffe()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 28, in import_caffe
    self.caffepb = import_caffepb()
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 12, in import_caffepb
    import caffepb
  File "/work/models/fluid/image_classification/caffe2fluid/kaffe/caffe/../../proto/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 654, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by qingqing01** [comment] 2018-05-11 01:43
@walloollaw Could you help to look this problem?

**Comment by walloollaw** [comment] 2018-05-11 02:31
This problem is about the version of installed protobuf is not compatible.
To solve this, please follow these steps:
- Rename *proto/caffepb.py* to *proto/caffe_pb2.py* and delete file *proto/caffepb.pyc*
- Edit the file *kaffe/caffe/resolver.py*
```
--- a/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py
+++ b/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py
@@ -9,8 +9,8 @@ def import_caffepb():
     p = os.path.dirname(p)
     p = os.path.join(p, '../../proto')
     sys.path.insert(0, p)
-    import caffepb
-    return caffepb
+    import caffe_pb2
+    return caffe_pb2
```
- Convert your model again

@sabreshao

**Comment by sabreshao** [comment] 2018-05-11 03:54
@walloollaw Thanks! The convert script can run further.
But it fails to convert AlexNet and Googlenet with below message:
Converting data...
Saving data...
Saving source...
Error encountered: No handler found for node kind: SoftmaxWithLoss (expected: map_softmax_with_loss)

Converting data...
Saving data...
Saving source...
Error encountered: No handler found for node kind: Accuracy (expected: map_accuracy)

**Comment by walloollaw** [comment] 2018-05-11 06:16
sorry for that the layers you mentioned above have not been supported yet.  Maybe you can create a ISSUE to mark that, i will support these in next week. Or you can implement that by yourself, more tips can be found about how to convert custom layers in README.md. @sabreshao

**Comment by sabreshao** [comment] 2018-05-16 10:32
@walloollaw issue created https://github.com/PaddlePaddle/models/issues/917

**Comment by walloollaw** [comment] 2018-05-17 02:56
ok,  too busy for this week. i will plan it.  
By the way, you can work around this for now,  steps may be like these:
- 1, remove the layers that don't support now(like softmaxwithloss and accuracy) in prototxt
- 2, convert it use the tool
- 3, load the model in xxx.py and xxx.npy just like *caffe2fluid/examples/imagenet/infer.py*
- 4, after make the fluid layer, you can add removed layers using fluid's api
- 5, save this fluid model or test it as you wish

this should be working because there is not weights for these layers @sabreshao

**Comment by shanyi15** [comment] 2018-08-15 09:54
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:54 UTC
