### ISSUE TITLE
ParallelDo vs. ParallelExecutor

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/models#970] opened 2018-06-07 09:45 UTC
In many training scripts there are two separate methods for training: `train_parallel_do()` and `train_parallel_exe()`. The former use `ParallelDo`, the latter `ParallelExecutor`. The documentation on both is rather sparse.
What is the difference between the two methods?

**Comment by luotao1** [comment] 2018-06-07 10:50
`ParallelDo` is for both CPU and GPU, `ParallelExecutor` is only for GPU now. But the GPU performance on `ParallelExecutor` is much better than `ParallelDo`.  And we will unify them after July 5th.

**Comment by wojtuss** [comment] 2018-06-22 11:14
@luotao1 , thanks!
But, does it mean that the script `models/fluid/image_classification/train.py` for training several models is designed only for GPU?

**Comment by luotao1** [comment] 2018-06-22 13:02
ParallelExecutor is OK for CPU now. You can refer to https://github.com/PaddlePaddle/Paddle/issues/11620 for benchmark.

**Comment by wojtuss** [comment] 2018-07-09 10:00
@luotao1 great news, thanks! :-) However, on CPU the ParallelExecutor seems to work only if the batch size equals the number of CPUs. Is there a way to set batch size to 128 on 40 CPUs for example?

**Comment by luotao1** [comment] 2018-07-25 06:00
Sorry for the late reply. There is no example to set batch size to 128 on 40 CPUs.

**Comment by shanyi15** [comment] 2018-08-15 10:05
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:05 UTC
Labels: intel
