### ISSUE TITLE
SSD infer.py does not work on CPU

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/models#702] opened 2018-03-09 11:59 UTC
I tried to use CPU for inference of SSD , using pretrained model of SSD.

so I modified  paddle init  from:
_-    paddle.init(use_gpu=True, trainer_count=1)_                                                                  
to:
_+    paddle.init(use_gpu=False, trainer_count=1)_                

Inference crashed with an error:
**Unknown pool type: cudnn-max-pool**

Crash goes away when vgg_ssd_net.py got all instances of following line modified **from:**

_-        pool_type=paddle.pooling.CudnnMax(),_                                                                         

**to:**
_+        pool_type=paddle.pooling.Max(),_

**Comment by peterzhang2029** [comment] 2018-03-14 03:04
Yes, this example only supports the CUDA GPU environment temporarily, and can not be trained using only CPU. This is mainly because the training is very slow using CPU only.  please refer to https://github.com/PaddlePaddle/models/tree/develop/ssd#training

**Comment by jczaja** [comment] 2018-03-14 07:34
Ok, but my use case was to do SSD infering using already trained SSD (as provided in your documentation). So having SSD trained on GPU and then performing inference on CPU should be a valid case?

**Comment by peterzhang2029** [comment] 2018-03-14 07:58
Thanks to point this.  Since both training process and inference of the SSD share the same model config, so it may not work with the CPU env even when doing prediction.   I'll try to contact the author of SSD to fix this.

**Comment by shanyi15** [comment] 2018-08-15 09:55
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:55 UTC
