### ISSUE TITLE
模型报错退出

### ISSUE THREAD

**Issue by yuanghbdbj** [PaddlePaddle/models#678] opened 2018-03-02 10:05 UTC
采用5000图片用image_classification示例程序训练alexnet模型（二分类），报错退出（200样本【非5000子集】成功跑完70轮）

1、报错如下：

```
Pass 0, Batch 3, Cost 20.500000, {'classification_error_evaluator': 0.3203125}
Thread [139688770483968] Forwarding __fc_layer_2__,
*** Aborted at 1519981919 (unix time) try "date -d @1519981919" if you are using GNU date ***
] Forwarding __fc_layer_2__,
*** Aborted at 1519981919 (unix time) try "date -d @1519981919" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f0b855a784e) received by PID 58007 (TID 0x7f0bd38b3700) from PID 18446744071651883086; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7f0b855a784e sgemm_kernel_SANDYBRIDGE

Floating point exception(core dumped)
```

2、添加error_clipping_threshold参数未有效解决
![default](https://user-images.githubusercontent.com/36145868/36893751-30101a54-1e44-11e8-8bda-1150ece26564.png)

**Comment by yeyupiaoling** [comment] 2018-03-04 12:19
@yuanghbdbj 
这个好像是浮点异常哦，是修改一下超参数，比如学习率，加正则

**Comment by yeyupiaoling** [comment] 2018-03-07 03:54
@yuanghbdbj 
也有可能是梯度问题，可以加上`BN`层

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:56 UTC
Labels: user
