### ISSUE TITLE
Retune parameters for CTC beam search decoder

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/models#218] opened 2017-08-31 04:10 UTC
The beam search decoder for deployment in [PR#139](https://github.com/PaddlePaddle/models/pull/139) takes advantage of trie tree as the data structure for prefix search and finite-state transducers for spelling correction, which speedup the decoding process and lower the WER. With a larger (compared with the model in [#115](https://github.com/PaddlePaddle/models/issues/115) ) well-trained acoustic model, parameters ```alpha``` and ```beta``` for the decoder are retuned on the development dataset of LibriSpeech, as shown in the figure below.  

![tune on larger model](https://user-images.githubusercontent.com/3064195/29906109-676990be-8e45-11e7-9cab-5a1d758dce19.png)

- ```alpha```: language model weight
- ```beta```: word insertion weight
- ```WER```: word error rate 

As usual, the WER is mainly affected by the variation of parameter ```alpha```. And the optimal parameters pair appears at ```(alpha,beta) = (2.15, 0.35)```, which produces a minimum WER **7.87%** on the test dataset of LibriSpeech, and attenuates the WER by **0.8%** compared to the prototype decoder in Python.

**Comment by shanyi15** [comment] 2018-08-15 09:58
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
Labels: model in process
