### ISSUE TITLE
example configuration for regression.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#10] opened 2017-04-21 11:05 UTC
- In this example, we would like to show how the do regression task in PaddlePaddle.

- Please refer to [this configuration file](https://github.com/lcy-seso/paddle_confs_v1/blob/master/regression/regression.conf) written in old PaddlePaddle API.

- Note that, currently PaddlePaddle provides two regression costs: mse and [huber loss](http://www.paddlepaddle.org/develop/doc/api/v2/config/layer.html#huber-cost). Please consider adding an example for huber loss.

- Please pull your codes and docs into the [regressoin](https://github.com/PaddlePaddle/models/tree/develop/regression) directory.

**Comment by chrisxu2016** [comment] 2017-05-03 05:39
@lcy-seso In the  [ old configuration file ](https://github.com/lcy-seso/paddle_confs_v1/blob/master/regression/regression.conf) ，I don't know which one is the    average layer in V2.  
>Layer(
>  inputs=[Input('input2_emb')],
>  name='input2_vec',
>  trans_type='non-seq',
>  bias=Bias(parameter_name='_avg.bias_basic', is_static=True),
>  active_type='tanh',
>  type='average',
>  average_strategy='sum', )

and  this example have two input layer, Which dataSet is suitable for this issue？

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
