### ISSUE TITLE
models 效果和精度持续测试机制及框架

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/models#521] opened 2017-12-06 07:51 UTC
paddle/models 最早定位是作为 Paddle 对外输出模型，便于用户直接修改使用，同时在模型的粒度上验证 paddle 可用性。

目前，models已经积累了相当数量的比较有应用价值的模型，但由于缺少精度和效果的测试机制，难以保证模型的效果，历史上也成出现过版本间效果差异较大的情况。

最新的 fluid 框架完善后，models 需要逐步迁移到 fluid 上，在这之前，我们可以尝试建立 models 的自动测试机制和框架，以实现

- 模型级别的效果验证
- 性能测试
- 宏观上的大功能验证

以长久保证 models 以及 Paddle 的实用性。

**Comment by wangkuiyi** [comment] 2017-12-06 08:20
It looks like we need many GPU server to enable such large-scale regression tests?

**Comment by Superjomn** [comment] 2017-12-06 09:12
Some initial ideas, each model will have three different sizes of the dataset.
- small size
- middle size
- full size

The small size dataset is very fast to run, the test framework will keep monitoring the performance of the small dataset every 1 day.

The middle size dataset will be checked before the releasement of every new version of Paddle or can be tested every week/month.

The full-size dataset is for users to train this model.

The model test framework's running will be decoupled from the test of the PaddlePaddle repository, it will run periodically.

@wangkuiyi

**Comment by Superjomn** [comment] 2017-12-07 03:46
The  goals of model contiguous integration framework are

1. keep validating the availability of models
2. make model development work more rigorous, (developers should care about the effectiveness too)
3. performance monitor of paddle at the model level

For each model, there will be three sizes of dataset:

1. small size of data, for quick validation
2. middle size of data for complete validation
3. full size of data for practical training

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:57 UTC
