### ISSUE TITLE
尝试应用weight layer报错

### ISSUE THREAD

**Issue by snowsteper** [PaddlePaddle/models#890] opened 2018-05-01 01:12 UTC
我尝试通过给样本赋予不同的重要性，通过
`cost = paddle.layer.classification_cost(input=prob, label=lbl, weight=wei)`
这里的wei定义为：
`wei = paddle.layer.data("weight", paddle.data_type.integer_value(1))`
运行的时候会报下面的信息
Thread [139955584042752] Forwarding __cost_0__,
不知道是出了什么问题

具体的报错信息如下：
[INFO 2018-05-01 09:01:54,403 train_conv_weighted.py:86] class number is : 3444.
[INFO 2018-05-01 09:01:54,403 train_conv_weighted.py:106] length of word dictionary is : 599999.
I0501 09:01:54.456384 16026 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
I0501 09:01:55.129230 16026 GradientMachine.cpp:94] Initing parameters..
I0501 09:02:06.899636 16026 GradientMachine.cpp:101] Init parameters done.
Thread [139955584042752] Forwarding __cost_0__, 
*** Aborted at 1525136527 (unix time) try "date -d @1525136527" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 16026 (TID 0x7f49f2df0700) from PID 8; stack trace: ***
    @     0x7f49f25a7160 (unknown)
    @     0x7f49b8f5bafb paddle::BaseMatrixT<>::dotMul()
    @     0x7f49b8d40a3c paddle::CostLayer::forward()
    @     0x7f49b8d80f4d paddle::NeuralNetwork::forward()
    @     0x7f49b8d81c63 paddle::GradientMachine::forwardBackward()
    @     0x7f49b9052a04 GradientMachine::forwardBackward()
    @     0x7f49b8c1e689 _wrap_GradientMachine_forwardBackward
    @     0x7f49f28c079f PyEval_EvalFrameEx
    @     0x7f49f28c40bd PyEval_EvalCodeEx
    @     0x7f49f28c1345 PyEval_EvalFrameEx
    @     0x7f49f28c40bd PyEval_EvalCodeEx
    @     0x7f49f28c1345 PyEval_EvalFrameEx
    @     0x7f49f28c40bd PyEval_EvalCodeEx
    @     0x7f49f28c1345 PyEval_EvalFrameEx
    @     0x7f49f28c40bd PyEval_EvalCodeEx
    @     0x7f49f28c1345 PyEval_EvalFrameEx
    @     0x7f49f28c1460 PyEval_EvalFrameEx
    @     0x7f49f28c40bd PyEval_EvalCodeEx
    @     0x7f49f28c41f2 PyEval_EvalCode
    @     0x7f49f28ecf42 PyRun_FileExFlags
    @     0x7f49f28ee2d9 PyRun_SimpleFileExFlags
    @     0x7f49f290400d Py_Main
    @     0x7f49f1b01bd5 __libc_start_main
    @           0x4007a1 (unknown)
    @                0x0 (unknown)

**Comment by shanyi15** [comment] 2018-08-15 09:54
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:54 UTC
