### ISSUE TITLE
crnn-ctc training: strange awk command and len(img_label_lines) != actual dataset size

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/models#974] opened 2018-06-08 10:23 UTC
Hi,

I have analysed a little bit the code of DataGenerator in ctc_reader.py and I have minor comments for the code there:

In line https://github.com/PaddlePaddle/models/blob/f93838a4258c2a197cfa9e14c244b4da7a042a88/fluid/ocr_recognition/ctc_reader.py#L67  `sizes` equals 0 if batch_size equals the total number of images in the dataset. I found this when I set batch_size equal to size of dataset. The result was that there was no iterations calculated at all (instead of one), because the loop in the next line is not executed. 

This has led me to the next thing:
In the line here https://github.com/PaddlePaddle/models/blob/f93838a4258c2a197cfa9e14c244b4da7a042a88/fluid/ocr_recognition/ctc_reader.py#L51 I have been testing what the command `sed 1,$((1 + RANDOM % 100))d` is supposed to do. 
I have left only 5 lines in the **img_label_list** file. I have then ran the command `cat /root/.cache/paddle/dataset/ctc_data/data/train.list | awk '{printf("%04d%.4f %s\n", $1, rand(), $0)}' | sort | sed 1,$(( RANDOM % 5))d` and it turns out that it outputs up to 4 lines. One of the lines is always missing. When I tried `sed 1,$(( RANDOM % 6))d` instead of `1,$(( RANDOM % 5))d`, I still got 4 or less lines. The conclusion is that there is always at least one file not present in output. I wonder if that was intended? **Does this lead to the first problem above**? Also, if I increase the number to 100, the probability of printing empty list increases drastically (I guesss that up to 95%). Is this intended behavior?

Also I found this:
https://github.com/PaddlePaddle/models/blob/f93838a4258c2a197cfa9e14c244b4da7a042a88/fluid/ocr_recognition/ctc_reader.py#L43, I found **awk** applying no change to the result of the previous command, as the file contains only 4 columns. 

I couldn't analyse any more of this code part because I had to return to my duties. I hope you can find this useful. :)

**Comment by shanyi15** [comment] 2018-08-15 09:53
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:53 UTC
Labels: intel
