### ISSUE TITLE
sequence_tagging_for_ner的download.sh的bug

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/models#567] opened 2018-01-05 08:32 UTC
按照说明：
为运行本例，请首先在data目录下运行download.sh脚本下载输入文本的词典和预训练的词向量。 完成后会将这两个文件一并放入data目录下，输入文本的词典和预训练的词向量分别对应：data/vocab.txt和data/wordVectors.txt这两个文件。
但是在data下执行download.sh后data里的文件是这样的
data  download.sh  target.txt  test  train  vocab.txt。没有wordVectors.txt
在执行
+ cp assignment2_release/data/ner/wordVectors.txt ./data
+ cp assignment2_release/data/ner/vocab.txt ./data的时候，会后一个覆盖掉前一个。
这里不确定是拷贝到原本的data里，还是还要在里面再新建一个data

**Comment by shanyi15** [comment] 2018-08-15 10:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:11 UTC
