### ISSUE TITLE
The numerical stability in ctc beam search decoder

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/models#95] opened 2017-06-14 16:49 UTC
The computation of probabilities in CTC beam search involves the addition and multiplication of very small numbers. To make sure the numerical stability, many other implementations first convert the  probabilities into log format, then execute the operation. 

In the Deep Speech 2 project, we implement two versions of beam search decoder, computing probability in the original and log form respectively. Currently, we use the the former for which is found to have a bit benefit in efficiency. But we also care about the numerical stability, so we have an [independent test](https://github.com/kuke/ctc_beam_search_decoder_num_test) to compare the two decoders with the ctc beam search decoder in TensorFlow.

Run ```test_ctc_beam_search_decoder.py```, the outputs look like
<img width="1025" alt="2017-06-15 9 37 50" src="https://user-images.githubusercontent.com/3064195/27163465-29084e04-51ba-11e7-946a-9ed65c666eb7.png">

When the length of input probability list is limited to several hundreds, the two decoders get almost the same scores and decoding results. Hence we believe that the numerical stability may be not a problem in the decoder right now, but we will be careful about it all the way.

**Comment by kuke** [comment] 2017-06-15 03:08
Run ```test_ctc_beam_search_decoder.py```, the output looks like
<img width="1025" alt="2017-06-15 9 37 50" src="https://user-images.githubusercontent.com/3064195/27163465-29084e04-51ba-11e7-946a-9ed65c666eb7.png">

When the length of input probability list is limited to several hundreds, the two decoders get the same score and decoding results. Hence we believe that the numerical stability may be not a problem in the decoder right now. But we will be careful about that all the way

**Comment by shanyi15** [comment] 2018-08-15 10:16
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:16 UTC
