### ISSUE TITLE
unify the way how demos runs in models repo and codes organization.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#330] opened 2017-09-27 09:14 UTC
- Currently, how each demos run in models repo varies from demo to demo. Except for some very complicated demo, for example, DS2, it is better to unify the organization of the code.
- At least the following work is required:
    - create command line interfaces for each example.
    - add docstring for each important function, and unify the style of docstring.  Keep the style be consistent with PaddlePaddle main repo.

**Comment by will-am** [comment] 2017-11-28 03:50
把代码组织成
train.py
infer.py
reader.py
network_conf.py
怎么样？

对于生成模型不用infer.py，用generate.py

但现在的代码里模型配置有叫network_conf.py的，也有叫model.py的，不知用哪个好？

**Comment by shanyi15** [comment] 2018-08-15 10:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:08 UTC
Labels: enhancement
