### ISSUE TITLE
"gen_chinese_poetry" load model slow

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/models#216] opened 2017-08-23 14:51 UTC
branch https://github.com/lcy-seso/models/tree/gen_chinese_poetry
run `generate.py`
- model size 193MB
- load time 12s

Slow code
```python
    with gzip.open(model_path, "r") as f:
        parameters = paddle.parameters.Parameters.from_tar(f)
```

**Comment by llxxxll** [comment] 2017-08-23 14:57
alike issue https://github.com/PaddlePaddle/Paddle/issues/2612

**Comment by lcy-seso** [comment] 2017-08-24 00:50
It seems that 12s is too long. I will check this.

**Comment by reyoung** [comment] 2017-08-25 05:31
@llxxxll 

You can create a global `Inference` instance then invoke `Inference.infer` or `Inferernce.iter_infer` time by time.

It will just load parameters once.

**Comment by lcy-seso** [comment] 2017-08-25 05:36
@reyoung https://github.com/lcy-seso/models/blob/gen_chinese_poetry/generate_chinese_poetry/generate.py#L68 currently the codes works as you suggested.

I think in @llxxxll's situation, he needs a server process to load the model, and then every time uses a  worker process to generate new sequence to avoid load the model again and again.

**Comment by shanyi15** [comment] 2018-08-15 09:58
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
Labels: enhancement, model in process
