### ISSUE TITLE
Download of librispeech model does not work

### ISSUE THREAD

**Issue by rsbhat78** [PaddlePaddle/models#520] opened 2017-12-06 06:10 UTC
Is it only me or anyone else faced an issue with downloading the librispeech model from http://cloud.dlnel.org/filepub/?uuid=17404caf-cf19-492f-9707-1fad07c19aae?

It always stops before completion with network error message.

**Comment by kuke** [comment] 2017-12-07 09:24
@rsbhat78 The DS2 project under this repo is no longer maintained, Please go to our new repo https://github.com/PaddlePaddle/DeepSpeech

**Comment by jayiind** [comment] 2017-12-08 10:20
@kuke Download from that link  also has the same issue.

**Comment by kuke** [comment] 2017-12-12 12:20
@jayiind Seems our DNS forwarding limits the download, you can set /etc/hosts file mannually adding:
```
180.76.189.142  cloud.dlnel.org
```
and try download again.

**Comment by shanyi15** [comment] 2018-08-15 09:57
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:57 UTC
