### ISSUE TITLE
Dataset copyrights/licenses

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/models#941] opened 2018-05-29 14:00 UTC
@luotao1 , models from this repo use various datasets for training and testing (flowers, cifar10, the one from `models/fluid/DeepASR/examples/aishell`, etc.). Are there any copyright restrictions in using these datasets (and generally any datasets that the scripts from this repository download when training a model) in our tests validating the models?

**Comment by luotao1** [comment] 2018-05-30 06:20
@wojtuss There is no copyright restrictions in using these datasets.

**Comment by wojtuss** [comment] 2018-05-30 08:39
@luotao1 OK. Are there any licenses for the datasets? There is also no info about it around the scripts, so I assume NO, but I want to be sure.

**Comment by luotao1** [comment] 2018-05-30 09:53
@wojtuss There are no licenses for the datasets.

**Comment by shanyi15** [comment] 2018-08-15 09:53
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:53 UTC
Labels: intel
