### ISSUE TITLE
SSD 模型参数调优问题

### ISSUE THREAD

**Issue by HUSTGOC** [PaddlePaddle/models#870] opened 2018-04-23 06:13 UTC
![image](https://user-images.githubusercontent.com/13493253/39109634-497fb79e-4700-11e8-9593-c37eabfb4c5b.png)

我的训练集图片是1280*720 的图片，然后我设置了图片大小为这个，然后就不停的包内存不足。
然后我调整 batch_size 为1 ，可以运行但是跑到第1个 Pass 就报这个错误。

**Comment by shanyi15** [comment] 2018-08-15 09:54
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:54 UTC
Labels: user
