### ISSUE TITLE
Profiling for RNN Search model for multi-gpu.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/models#757] opened 2018-03-22 04:31 UTC
| pass_id |single-gpu | two-gpu | three-gpu | four-gpu |
| - | - | - | - | - |
|0|207.810512|193.126689| 153.078007 | 131.083838 |
|1|212.449378|191.684570| 151.617278 | 129.824058 |
|2|209.937869|190.296914| 151.363250 | 129.944818 |
|3|200.752512|196.673491|151.120727 | 130.697326 |
|4|201.428616|193.513692| 155.460599 | 131.675840 |
|avg:|206.4757774|193.0590712|152.5279722| 130.645176|

GPU: TITAN X (Pascal)

paddlepaddle commit id: cb3bbbd5c6690943d9ac14849e4f6eca7b3ba3bf

**Comment by shanyi15** [comment] 2018-08-15 09:55
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:55 UTC
