### ISSUE TITLE
写模型到本地目录的时候崩溃

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/models#163] opened 2017-07-16 01:33 UTC
第一轮训练完成之后，写入文件，崩溃，代码是：
```python
with gzip.open("dssm_%s_pass_%05d.tar.gz" %
(model_save_name_prefix, event.pass_id), "w") as f:
parameters.to_tar(f)
```
错误日志是：
```text
[INFO 2017-07-13 15:26:48,320 train.py:199] Pass 0, Batch 4000, Cost 0.530298, {'auc_evaluator_0': 0.7309514880180359, 'classification_error_evaluator': 0.2705000042915344}

(paddle_box) (paddle_box) tail log.bigram
num_passes=num_passes)
File "/home/yanchunwei/third_party/paddle_env/python27/lib/python2.7/site-packages/paddle/v2/trainer.py", line 175, in train
event_handler(v2_event.EndPass(pass_id, evaluator=pass_evaluator))
File "train.py", line 211, in _event_handler
parameters.to_tar(f)
File "/home/yanchunwei/third_party/paddle_env/python27/lib/python2.7/site-packages/paddle/v2/parameters.py", line 274, in to_tar
self.serialize(nm, buf)
File "/home/yanchunwei/third_party/paddle_env/python27/lib/python2.7/site-packages/paddle/v2/parameters.py", line 256, in serialize
f.write(param.tostring())
OverflowError: length too large
```

用的DSSM模型，字典维度200w

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
