### ISSUE TITLE
如何编译成android库

### ISSUE THREAD

**Issue by vesung** [PaddlePaddle/models#905] opened 2018-05-11 11:29 UTC
能不能编译成android平台库

**Comment by luotao1** [comment] 2018-05-11 11:38
可以参考 http://www.paddlepaddle.org/docs/develop/mobile/README.cn.html

**Comment by vesung** [comment] 2018-05-14 02:35
@luotao1 请问DeepSpeech可以编译成android库吗？

**Comment by luotao1** [comment] 2018-05-14 04:21
您好，只有paddle的c++代码本身能编译成android库，如果有python逻辑，都需要用c++或者java重新实现一遍。对于DeepSpeech来说，有很多python逻辑，而且decoder部分还有很多依赖，因此不能编译成android库。

**Comment by shanyi15** [comment] 2018-08-15 09:54
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:54 UTC
