### ISSUE TITLE
Speedup ratio on multiple GPUs

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/models#669] opened 2018-02-26 04:58 UTC
Some important arguments:

```
batch_size: 32
device: GPU
first_batches_to_skip: 1
hidden_dim: 1024
learning_rate: 0.002
max_batch_num: 10
mean_var: data/global_mean_var_search26kHr
minimum_batch_size: 1
parallel: True
proj_dim: 512
stacked_num: 5
```

Speedup on different number of GPUs:

| GPUs   |  Performance (frames/s)   |   Speedup ratio |
|:--------:|:---------------------------:|:-----------------:|
| 1      |  2590.32                  |     1.0x        |
| 2      |  3004.38                  |     1.16x       |
| 3      |  3183.40                  |     1.23x       |
| 4      |  3459.31                  |     1.36x       |

**Comment by kuke** [comment] 2018-02-28 11:39
Maybe fixing the total batch size is not the proper way to measure the speedup ratio. Here we fix the number of samples per GPU to 32 and carry out the profiling again:

|  GPUs  |  Batch size   |  Performance(frames/s) | Speedup Ratio |
|:--------:|:---------------:|:--------------:|:---------------:|
|   1      |      32         |    2584.18   |     1.0x      |
|   2      |     64          |    4696.14   |     1.82x     |
|   3      |        96       |    6635.73   |     2.56x     | 
|   4      |    128          |    6862.32   |    2.65x      |

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:56 UTC
Labels: DeepASR
