### ISSUE TITLE
CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 6) Cudnn Error

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#400] opened 2017-10-24 12:32 UTC
```------------------------------------------------
I1024 12:30:02.643218    58 Util.cpp:166] commandline:  --use_gpu=1 --rnn_use_batch=True --trainer_count=8 
F1024 12:30:02.761147    58 hl_cuda_cudnn.cc:186] Check failed: CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 6) Cudnn Error: CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7f1b059dc12d  google::LogMessage::Fail()
    @     0x7f1b059de478  google::LogMessage::SendToLog()
    @     0x7f1b059dbc1b  google::LogMessage::Flush()
    @     0x7f1b059df34e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1b0597cb65  hl_cudnn_init()
    @     0x7f1b05987b2f  hl_create_global_resources()
    @     0x7f1b05988494  hl_specify_devices_start()
    @     0x7f1b0598876d  hl_start()
    @     0x7f1b0590c6fe  paddle::initMain()
    @     0x7f1b059c2691  initPaddle()
    @     0x7f1b054845b7  _wrap_initPaddle
    @           0x4c468a  PyEval_EvalFrameEx
    @           0x4c9d8f  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4de6fe  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4c6ad1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4c2509  PyEval_EvalCode
    @           0x4f1def  (unknown)
    @           0x4ec652  PyRun_FileExFlags
    @           0x4eae31  PyRun_SimpleFileExFlags
    @           0x49e14a  Py_Main
    @     0x7f1b21c88830  __libc_start_main
    @           0x49d9d9  _start
    @              (nil)  (unknown)
run_test.sh: line 38:    58 Aborted                 (core dumped) CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -u test.py --batch_size=16 --trainer_count=8 --beam_size=500 --num_proc_bsearch=8 --num_proc_data=8 --num_conv_layers=2 --num_rnn_layers=3 --rnn_layer_size=2048 --alpha=2.15 --beta=0.35 --cutoff_prob=1.0 --use_gru=False --use_gpu=True --share_rnn_weights=True --test_manifest='data/tiny/manifest.tiny' --mean_std_path='data/tiny/mean_std.npz' --vocab_path='data/tiny/vocab.txt' --model_path='checkpoints/params.pass-19.tar.gz' --lang_model_path='models/lm/common_crawl_00.prune01111.trie.klm' --decoding_method='ctc_beam_search' --error_rate_type='wer' --specgram_type='linear'
Failed in evaluation!
```

**Comment by lezasantaizi** [comment] 2017-10-25 01:25
我可以关闭cudnn吗？

**Comment by pkuyym** [comment] 2017-10-26 07:15
img_conv层可以指定类型，参考
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2476

**Comment by shanyi15** [comment] 2018-08-15 09:57
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:57 UTC
Labels: user
