### ISSUE TITLE
Some candidates  for Paddle Models  repository.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#532] opened 2017-12-11 06:40 UTC
We are going to find more partners to help us add more popular models into the Paddle Models repository. Here are some candidates. If anyone has any suggestion please comment this issue. Thank you. 

--- 

### Understanding / Generalization / Transfer
- Distilling the knowledge in a neural network (2015), G. Hinton et al. [[pdf]](http://arxiv.org/pdf/1503.02531)

### Optimization / Training Techniques
- Training very deep networks (2015), R. Srivastava et al. [[pdf]](http://papers.nips.cc/paper/5850-training-very-deep-networks.pdf)

### Convolutional Neural Network Models
- Identity Mappings in Deep Residual Networks (2016), K. He et al. [[pdf]](https://arxiv.org/pdf/1603.05027v2.pdf)

### Segmentation
- Fully convolutional networks for semantic segmentation (2015), J. Long et al. [pdf](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Long_Fully_Convolutional_Networks_2015_CVPR_paper.pdf)

### Image / Video
- Show, attend and tell: Neural image caption generation with visual attention (2015), K. Xu et al. [[pdf]](http://arxiv.org/pdf/1502.03044)
- Show and tell: A neural image caption generator (2015), O. Vinyals et al. [[pdf]](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Vinyals_Show_and_Tell_2015_CVPR_paper.pdf)

### Natural Language Processing / RNNs
- Teaching machines to read and comprehend (2015), K. Hermann et al. [[pdf]](http://papers.nips.cc/paper/5945-teaching-machines-to-read-and-comprehend.pdf)
- A convolutional neural network for modeling sentences (2014), N. Kalchbrenner et al. [[pdf]](http://arxiv.org/pdf/1404.2188v1)
- Distributed representations of words and phrases and their compositionality (2013), T. Mikolov et al. [[pdf]](http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)

### Mobile
- SqueezeNet: AlexNet-level accuracy with 50x fewer parameters and< 1MB model size (2016), F. Iandola et al. [[pdf]](http://arxiv.org/pdf/1602.07360)

### Classic Paper
- Natural language processing (almost) from scratch (2011), R. Collobert et al. [[pdf]](http://arxiv.org/pdf/1103.0398)
- Stacked denoising autoencoders: Learning useful representations in a deep network with a local denoising criterion (2010), P. Vincent et al. [[pdf]](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.297.3484&rep=rep1&type=pdf)

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:56 UTC
