### ISSUE TITLE
Can not save inference model in multi-GPU mode

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/models#724] opened 2018-03-13 03:01 UTC
Error complaint:

```
-----------  Configuration Arguments -----------
batch_size: 32
checkpoints: ./checkpoints
device: GPU
hidden_dim: 1024
infer_models: ./infer_models
init_model_path: None
learning_rate: 0.002
mean_var: data/global_mean_var_search26kHr
minimum_batch_size: 1
parallel: True
pass_num: 100
print_per_batches: 100
proj_dim: 512
stacked_num: 5
train_feature_lst: data/feature.lst
train_label_lst: data/label.lst
val_feature_lst: data/val_feature.lst
val_label_lst: data/val_label.lst
------------------------------------------------
..................................................................Traceback (most recent call last):
  File "train.py", line 265, in <module>
    train(args)
  File "train.py", line 252, in train
    [prediction], exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/io.py", line 342, in save_inference_model
    prepend_feed_ops(inference_program, feeded_var_names)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/io.py", line 272, in prepend_feed_ops
    out = global_block.var(name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/framework.py", line 708, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var feature not in this block
```

**Comment by shanyi15** [comment] 2018-08-15 10:06
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:06 UTC
Labels: DeepASR
