### ISSUE TITLE
implementation of weighted cost

### ISSUE THREAD

**Issue by jmliu88** [PaddlePaddle/models#321] opened 2017-09-26 07:21 UTC
Say I have a prediction sequence $\hat{Y} = [\hat{y_1}, ... , \hat{y_T}]$ which comes from paddle.v2.layer.lstmemory, a target sequence $Y = [y_1, ..., y_T]$ comes from 
```python
paddle.layer.data( name='target', type=paddle.data_type.integer_value_sequence(label_dict_len))
```
, and a weight sequence $W=[w_1, ..., w_T]$. Is there a way to calculate cost as 
$\sum_t w_t*cross_entropy(\hat{y_t}, y_t)$ ?

Thanks

**Comment by lcy-seso** [comment] 2017-09-26 09:21
- cost entropy cost has a keyword argument: weight whose type is LayerOutput. 
- You can define a data layer  to feed sample weights to the cost layers like this,

```python
weight = paddle.layer.data(name='sample_weights', type=dtype.dense_vector(1))

... other codes ....

cost = cross_entropy(input=input_hidden_vectors, label=label_layer, weight=sample):
```

**Comment by shanyi15** [comment] 2018-08-15 10:08
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:08 UTC
Labels: user
