### ISSUE TITLE
examples/librispeech/run_infer.sh core dump

### ISSUE THREAD

**Issue by jayiind** [PaddlePaddle/models#523] opened 2017-12-07 03:19 UTC
sh run_infer.sh as well as run_infer_golden.sh are not successfully executed. Ressults in core_Dump with teh following error
F1207 08:41:56.133008  8493 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: mkldnn_conv
*** Check failure stack trace: ***
    @     0x7f565498c9ad  google::LogMessage::Fail()
    @     0x7f565499045c  google::LogMessage::SendToLog()
    @     0x7f565498c4d3  google::LogMessage::Flush()
    @     0x7f565499196e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f56546b683b  paddle::Layer::create()
    @     0x7f5654740408  _ZZN6paddle13NeuralNetwork4initERKNS_11ModelConfigESt8functionIFviPNS_9ParameterEEERKSt6vectorINS_19enumeration_wrapper13ParameterTypeESaISB_EEbENKUlRKNS_11LayerConfigEE_clESI_
    @     0x7f56547418bf  paddle::NeuralNetwork::init()
    @     0x7f565476a29f  paddle::GradientMachine::create()
    @     0x7f5654969425  GradientMachine::createFromPaddleModelPtr()
    @     0x7f565496960f  GradientMachine::createByConfigProtoStr()
    @     0x7f56545f8de7  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4cb755  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4de858  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4f452e  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4f42a7  (unknown)
    @           0x4b669c  (unknown)
    @           0x4b0c93  PyObject_Call
    @           0x4c9f9f  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
Aborted (core dumped)

Any help here would be appreciated

**Comment by pkuyym** [comment] 2017-12-07 05:03
Please check our new repo https://github.com/PaddlePaddle/DeepSpeech

**Comment by shanyi15** [comment] 2018-08-15 09:56
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:56 UTC
