### ISSUE TITLE
generate_chinese_poetry AssertionError

### ISSUE THREAD

**Issue by shashlik007** [PaddlePaddle/models#976] opened 2018-06-11 01:36 UTC
File "train.py", line 172, in <module>
    train(args.num_passes, args.batch_size, args.use_gpu, args.trainer_count, args.save_dir_path, args.encoder_depth, args.decoder_depth, args.train_data_path, args.word_dict_path)
  File "train.py", line 128, in train
    max_length=9)
  File "/home/map/chenjiachuan/models-develop/generate_chinese_poetry/network_conf.py", line 127, in encoder_decoder_network
    input=group_inputs + [trg_emb])
  File "/home/map/wangxiaomin/soft/paddle/python27/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/map/wangxiaomin/soft/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/map/wangxiaomin/soft/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 3460, in recurrent_group
    assert is_single_input(each_input)
AssertionError

**Comment by shashlik007** [comment] 2018-06-11 01:38
我的参数输入如下：
args: Namespace(batch_size=6, decoder_depth=3, encoder_depth=3, init_model_path='', num_passes=5, save_dir_path='models', train_data_path='data/poems.txt.head', trainer_count=1, use_gpu=False, word_dict_path='data/dict.txt.head')

**Comment by shateng** [comment] 2018-07-25 09:48
![image](https://user-images.githubusercontent.com/25278878/43193546-de7d39b8-9032-11e8-80c7-8ccecf413e93.png)
demo里的这段代码有问题吧？怎么列表里这么多奇怪的东西？

**Comment by shanyi15** [comment] 2018-08-15 09:53
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:53 UTC
