### ISSUE TITLE
Does beam_search support convolutional decoder?

### ISSUE THREAD

**Issue by byzhang** [PaddlePaddle/models#187] opened 2017-08-05 04:05 UTC
As used in https://arxiv.org/abs/1705.03122?
The key difference may be the rnn decoder depends on only one previous state, while conv decoder depends on many previous states?

**Comment by lcy-seso** [comment] 2017-08-05 08:32
- I think a convolutional layer cannot be directly added into  PaddlePaddle‘s [beam_search](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#beam-search) API, but you can call `Inference` API to implement beam search process outside Paddle.

- Here is an example of generating sequences by RNN language model which implements beam search by using PaddlePaddle's `Inference` API outside PaddlePaddle. https://github.com/PaddlePaddle/models/blob/develop/generate_sequence_by_rnn_lm/generate.py#L60 , I think a convolutional decoder can be implemented like this example.

- Some notes:
    - In the example: generating sequences by RNN language model listed above, every time one word is predicted, and then it is added to the current generated prefix. This prefix is then fed to an LSTM unit, this process always re-computed the already generated prefix, so it requires extra computations.
    - This problem can be avoided if you train the CNN decoder implemented by `recurrent_group` with the step function made up of basic fully connected layer instead of directly using a sequence convolution layer. And then implement a beam search outside PaddlePaddle.

- If you think we'd better provide an example, please feel free to let me know. I am very glad to add one.

---
- Currently, I am not very sure about every technical detail of the convolutional decoder in this paper, let me first list some basic facts of [beam_search](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#beam-search) in PaddlePaddle, and later I will check how to directly add a convolutional decoder into `beam_search` API as in this paper (I think maybe some tricks are needed).

    * If you mean using [beam_search](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#beam-search) API as in NMT example like [this one]( https://github.com/PaddlePaddle/models/blob/develop/nmt_without_attention/network_conf.py#L101), I think the answer is no.
  - This  [beam_search](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#beam-search) API ONLY works in `recurrent_group` for text generation task. If you do not use `recurrent_group` to define the network topology, beam_search cannot work.
  - `recurrent_group` is very like a `while_loop` operator in TensorFlow, it allows user define computations in one time step, and PaddlePaddle takes charges to iterate over the input sequence. In `recurrent_group`, `memory` is used to retrieve a layer's output in previous time step.
  - `memory` in PaddlePaddle only  retrieves a layer's output in previous time step, it cannot 'memorize' a layer's output more than that.

**Comment by byzhang** [comment] 2017-08-05 15:56
Thank you! We will read through your comments.

**Comment by shanyi15** [comment] 2018-08-15 09:58
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
Labels: user
