### ISSUE TITLE
example configuration for seq2seq.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#12] opened 2017-04-21 11:17 UTC
- In this example, we would like to show some different configuration for seq2seq task.
- Please refer to the following two configuration files:
    1. [grid lstm](https://github.com/lcy-seso/paddle_confs_v1/blob/master/seq2seq/grid_lstm.conf) written in old PaddlePaddle API.
    2. [encoder-decoder without attention](https://github.com/lcy-seso/paddle_confs_v1/blob/master/seq2seq/nmt_without_attention.conf) written in old PaddlePaddle API.
- The example **must** include the training and the generating process.
- Please pull your codes and docs into the [seq2seq](https://github.com/PaddlePaddle/models/tree/develop/seq2seq) directory.

**Comment by lcy-seso** [comment] 2017-05-02 03:06
please use WMT14 dataset for this example, you can refer to book chapter [machine translation]( https://github.com/PaddlePaddle/book/tree/develop/07.machine_translation).

wmt14 dataset has already been pre-processed and is included into paddle.dataset package. This is a simple example.

```python
wmt14_reader = paddle.batch(
        paddle.reader.shuffle(
            paddle.dataset.wmt14.train(dict_size=dict_size), buf_size=8192),
        batch_size=5)
```

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
