### ISSUE TITLE
各个模型的目录结构、文件名称、运行方式需要统一

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/models#174] opened 2017-07-20 10:05 UTC
现在模型的运行方式有：
`python train.py`
`python xxx.py`
`python xxx.py -y 0 --model_arch 0`
`./run.sh`
这里最好统一一下，此外模型的train和infer最好都分开，并都命名为相同的名字（train.py, infer.py），总之，models中各个模型的目录结构、文件名称、运行方式需要统一。

**Comment by lcy-seso** [comment] 2017-08-05 08:42
谢谢你！确实如此。我会接手完成这个工作。

**Comment by shanyi15** [comment] 2018-08-15 09:59
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:59 UTC
