### ISSUE TITLE
sequence_tagging_for_ner/infer.py预测出错

### ISSUE THREAD

**Issue by hujq1002** [PaddlePaddle/models#590] opened 2018-01-23 08:31 UTC
训练日志中测试集上error < 0.05，但是测试集通过sequence_tagging_for_ner/infer.py的输出标签大部分都是错的。
在infer.py的第15行，将start_id 赋值为0，这样每次输出都是从probs的初始位置开始，没有输出正确的预测标签。

**Comment by shanyi15** [comment] 2018-08-15 10:11
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 10:11 UTC
