### ISSUE TITLE
Evaluate internel mandarin dataset (~12k hours)

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/models#394] opened 2017-10-23 04:25 UTC
Regular Dev (Randomly select 2000 examples)

| Model | Decode Type | CER |
| -- | -- | -- |
| Pass-4 | Greedy | 0.170827
| Pass-5-8000 | Greedy | 0.181563
| Continue-Pass-1 (About Pass-6) | Greedy | 0.167423
| Continue-Pass-3 (About Pass-8) | Greedy | 0.168330
| Continue-Pass-2 (About Pass-7) | Greedy | 0.161796
| Continue-8x-Pass-4-2000 (About Pass-9) | Greedy | 0.167176

Aishell Test (Randomly select 2000 examples)

| Model | Decode Type | CER |
| -- | -- | -- |
| Pass-4 | Beam Search (default) | 0.301863
| Pass-5-8000 | Beam Search (default) | 0.312483
| Continue-Pass-1 | Beam Search (default) | 0.295325
| Continue-Pass-1 | Greedy | 0.410359

**Comment by shanyi15** [comment] 2018-08-15 09:57
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Closed as completed by shanyi15** 2018-08-15 09:58 UTC
